### ISSUE TITLE
Failed to call service light/turn_off. [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by milnovako** [tomasbedrich/home-assistant-skydance#1] opened 2020-11-28 09:34 UTC
After integration everything works ok, but after a while I get the error "Failed to call service light / turn_off. [Errno 32] Broken pipe", after restarting the home assistant everything works ok for a while, and again an error occurs. Do you have any idea ?

![Screenshot 2020-11-28 104051](https://user-images.githubusercontent.com/13822352/100498971-3c1eaa80-3166-11eb-988f-8ad67a95bd25.png)

**Comment by tomasbedrich** [comment] 2020-11-29 23:38
Hi @milnovako, thanks for your report. Also thank you for using this very alpha version of the integration.

I am almost 100% sure, that this is caused by streams being broken sometime in between the integration installation and usage. I was expecting this: [this is the TODO](https://github.com/tomasbedrich/home-assistant-skydance/blob/master/custom_components/skydance/__init__.py#L31) which I wrote for that.

I haven't hit this issue (until today 😄) since my home network is probably a bit more stable than yours. But I am going to solve it soon.

**Comment by tomasbedrich** [comment] 2020-12-01 02:24
Working on it. It needs some major changes to underlaying library as well: https://github.com/tomasbedrich/skydance/pull/4

**Comment by tomasbedrich** [comment] 2020-12-28 01:40
Should be fixed in version 1.0.0. Please try.

Beware you need to remove the integration completely prior upgrading to that version.

**Comment by qatryk** [comment] 2021-01-13 22:40
Hi @tomasbedrich,
First great job - i hope you will develop this integration. I have similar problem. I'm using 1.1.2 version. After a while integration I have a lost connection:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skydance/session.py:23
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:30:29 (2 occurrences)
Last logged: 23:27:45

[1779168112] [Errno 110] Operation timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/skydance/network/session.py", line 48, in write
    await writer.drain()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 230, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/skydance/light.py", line 140, in async_turn_on
    await self._turn_on()
  File "/config/custom_components/skydance/light.py", line 149, in _turn_on
    await self._session.write(cmd)
  File "/config/custom_components/skydance/session.py", line 23, in write
    res = await super().write(data)
  File "/usr/local/lib/python3.8/site-packages/skydance/network/session.py", line 51, in write
    await self._close_connection()
  File "/usr/local/lib/python3.8/site-packages/skydance/network/session.py", line 32, in _close_connection
    await writer.wait_closed()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
TimeoutError: [Errno 110] Operation timed out

**Comment by milnovako** [comment] 2021-01-15 18:57
Hi @tomasbedrich,
same problem again.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skydance/session.py:23
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:49:25 (19 occurrences)
Last logged: 19:52:27

[139680185733424] [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/skydance/network/session.py", line 48, in write
    await writer.drain()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 230, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/skydance/light.py", line 140, in async_turn_on
    await self._turn_on()
  File "/config/custom_components/skydance/light.py", line 149, in _turn_on
    await self._session.write(cmd)
  File "/config/custom_components/skydance/session.py", line 23, in write
    res = await super().write(data)
  File "/usr/local/lib/python3.8/site-packages/skydance/network/session.py", line 51, in write
    await self._close_connection()
  File "/usr/local/lib/python3.8/site-packages/skydance/network/session.py", line 32, in _close_connection
    await writer.wait_closed()
  File "/usr/local/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by tomasbedrich** [comment] 2021-01-15 20:43
Happened to me too today: https://gist.github.com/tomasbedrich/bc32301c39e154afe6bc121b71c5e0f6

I will take a look at it soon. In meantime, please just "Reload" the integration if this happens.

**Comment by tomasbedrich** [comment] 2021-01-17 21:04
@qatryk @milnovako Can you please try version 1.1.3 whether it fixes the problem?

**Comment by milnovako** [comment] 2021-01-18 10:33
12 hours already working without error :)

**Comment by qatryk** [comment] 2021-01-18 21:18
Unfortunnetly, for me there is still a problem. Now I don't get any error massage but after about 10 minutes light don't turn on/off. I have logger in debug mode and it looks like evything ok:
2021-01-18 22:02:37 DEBUG (MainThread) [custom_components.skydance.light] Powering off zone=skydance-f0fe6b8b5242-4
2021-01-18 22:02:40 DEBUG (MainThread) [custom_components.skydance.light] Powering on zone=skydance-f0fe6b8b5242-4
2021-01-18 22:13:52 DEBUG (MainThread) [custom_components.skydance.light] Powering on zone=skydance-f0fe6b8b5242-3
2021-01-18 22:13:52 DEBUG (MainThread) [custom_components.skydance.light] Powering off zone=skydance-f0fe6b8b5242-3

but as I wrote - second time lights don't react.

**Comment by tomasbedrich** [comment] 2021-01-19 08:59
I see. That said, I can try reworking the session to proactively close the connection after a while (10s) and automatically re-open it when communication is desired.

**Comment by milnovako** [comment] 2021-01-19 14:12
it still works :)

**Comment by tomasbedrich** [comment] 2021-08-20 22:29
Hi everyone, what is the situation after a longer time?

**Closed as completed** 2023-08-02 22:25 UTC
